export const cartActionTypes = {
  SHOW_DROPDOWN: "SHOW_DROPDOWN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_SINGLE_ITEM: "REMOVE_SINGLE_ITEM",
  UPDATE_SHOP_DATA: "UPDATE_SHOP_DATA",
  CLEAR_CART: "CLEAR_CART"
};
