export const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SHOW_DROPDOWN: "SHOW_DROPDOWN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_SINGLE_ITEM: "REMOVE_SINGLE_ITEM",
};
